private - initialization
initErrorConstants
		LOCKERR := -76.
		READ_ONLY := -75.

		CANTOPEN := -74.
		FULL := -73.
		VM_ERR := -71.
		COMPILE_ERR := -70.

		DONE := -28.
		CORRUPT := -24.
		PERM := -19.
		EOF := -18.
		NOTIMPLEMENTED := -17.
      BUSY := -14.
		UNKNOWN := -13.

		EXISTS := -11.
		ABORT := -10.
		INVALID := -9.
		LIMIT := -7.
		LOCKED := -4.
		EMPTY := -3.
		IOERR := -2.
		NOMEM := -1.
		NOOP := -20.
		NOTFOUND := -6
		
		
		
		
		
		