catalog
catalogChangeLog
		
 ^ '- Version 1.1
[[[
(ConfigurationOfPunQLite project version: ''1.1'') load
]]]
- Version 1.1.1
[[[
(ConfigurationOfPunQLite project version: ''1.1.1'') load
]]]
- Version 1.1.2
[[[
(ConfigurationOfPunQLite project version: ''1.1.2'') load
]]]
- Version 1.1.3
[[[
(ConfigurationOfPunQLite project version: ''1.1.3'') load
]]]

- Version 1.1.4
[[[
(ConfigurationOfPunQLite project version: ''1.1.4'') load
]]]

- Version 2.0
[[[
(ConfigurationOfPunQLite project version: ''2.0'') load
]]]
'
	
	