catalog
catalogDescription

^ 
'UnQLite binding for Pharo Smalltalk. UnQLite is a fast, lightweight, portable, embedded KVS with a simple scripting engine (Jx9). By using PunQLite, you can store/load lots of data as if just using a normal Dictionary.

PunQLite uses UnQLite shared library. If you have no time to compile, just get pre-built binary from the github project page (https://github.com/mumez/PunQLite).

'